name: Rust Linux Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: |
          cd rust-sdk
          cargo build --release --verbose

      - name: Run tests
        run: |
          cd rust-sdk
          cargo test --verbose

      - name: Create archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd rust-sdk/target/release
          tar -czvf rust-sdk-linux.tar.gz *

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./rust-sdk/target/release/rust-test
            ./rust-sdk/target/release/rust-sdk-linux.tar.gz
          name: Release ${{ github.ref_name }} (Linux)
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}