name: Rust macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: |
          cd rust-sdk
          cargo build --release --verbose

      - name: Run tests
        run: |
          cd rust-sdk
          cargo test --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-sdk-macos
          path: rust-sdk/target/release/*

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(grep version rust-sdk/Cargo.toml | head -n 1 | awk '{print $3}' | sed 's/"//g')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rust-sdk/target/release/rust-test
          name: Release ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}